#!/usr/bin/env php
<?php
ini_set('assert.exception', 1);
require_once('vendor/autoload.php');

use Symfony\Component\Console\Application;
use function PHPAssert\Console\Utils\App\getApp;

$app = getApp();
$app->run();
